5.846795"461003639959": {"error": "ERROR_DENIED", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас есть неоплаченный в течение 5 дней с момента активации «Обещанный платеж»."},
4.738477"461010230585": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818332948", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.973307"461000249378": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.308001"461004514444": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818335239", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.486136"461000249497": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.258876"461004251843": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818336996", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.2836"461004216817": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818339272", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
4.121459"461000052951": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
0.28582"461002407783": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818343699", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.443531"461000363036": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
5.108453"461013061096": {"error": "ERROR_DENIED", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас есть неоплаченный в течение 5 дней с момента активации «Обещанный платеж»."},
0.761532"461002965763": {"error": "ERROR_DENIED", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас есть неоплаченный в течение 5 дней с момента активации «Обещанный платеж»."},
1.912752"461012949055": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818353936", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.120095"461003055051": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.719237"461002916308": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818357793", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.711415"461002916338": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818358505", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.427816"461002951781": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.341738"461004825225": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818360292", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.256677"461002653400": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818360554", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.503566"461001379908": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818363064", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
3.63741"461001398434": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.298193"461004504315": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818366998", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
3.554741"461001361757": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818370559", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.287878"461004359289": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818370863", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.261802"461004359334": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818371120", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.282382"461004343726": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818371416", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.29646"461002637893": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818371703", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.281785"461002657048": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818371992", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.277003"461004504214": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818372272", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.266313"461004734575": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818372544", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.34495"461004823695": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818372895", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
3.481898"461004769556": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.00674"461004769567": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.304948"461002126461": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818377715", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.244023"461002126472": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818377960", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.088892"461002115718": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818380044", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.2861"461004866225": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818380333", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
3.556953"461014760230": {"error": "ERROR_DENIED", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас есть неоплаченный в течение 5 дней с момента активации «Обещанный платеж»."},
0.287019"461004616789": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818384197", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.271438"461004700535": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818384466", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.262896"461004718880": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818384742", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.278578"461004718890": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818385026", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.870447"461002541888": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.526944"461002518401": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818389432", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
4.681987"461002505805": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818394119", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
8.832208"461002524424": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
0.918326"461002524443": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.650986"461004894762": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818405530", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.499899"461004769025": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818407041", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.289413"461004396548": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818407337", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.276592"461002690674": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818407610", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.271415"461001360440": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818407895", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.376271"461001362393": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818410263", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.368791"461002673522": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818410640", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.291026"461002692120": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818410934", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.288002"461001373402": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818411236", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.346514"461001374975": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818411584", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.342288"461001393627": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818411927", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.26263"461004359560": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818412206", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.270324"461004523606": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818412475", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.271065"461004523652": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818412747", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.281153"461004397054": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818413033", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.415299"461001250438": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818521053", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.303347"461001250495": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818521376", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
3.919629"461000366796": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818525300", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
4.251312"461003623529": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.798262"461003673797": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818531358", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
6.011296"461003391497": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.381393"461003391059": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818538752", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
5.47607"461003642165": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
3.872637"461000290237": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
3.317627"461000229947": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.313359"461004515977": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818551753", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.271545"461004531951": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818552035", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
5.540552"461003621750": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818557570", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
5.51774"461003640028": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
5.466506"461003640087": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.278923"461000230004": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.450687"461000249593": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.30641"461001218797": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818571616", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.256296"461001238023": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818571885", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.272445"461001247370": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818572162", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.285263"461001216242": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818572451", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.257355"461001233709": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818572716", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.272705"461001237985": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818572985", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.286385"461001214986": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818573279", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.19294"461001250467": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818575474", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.30223"461000529122": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818575785", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.600305"461010610829": {"error": "ERROR_DENIED", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас есть неоплаченный в течение 5 дней с момента активации «Обещанный платеж»."},
0.324589"461000472331": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818578723", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.248898"461001219679": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818578983", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.304348"461001246512": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818579294", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
3.330385"461000366824": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
0.28781"461004861410": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818582912", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.299656"461004861425": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818583229", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.101041"461004212639": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818585318", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.298352"461004889037": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818585640", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
7.68241"461004657057": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
4.464946"461004692676": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
1.774141"461013526971": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818599565", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
3.903278"461004105192": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
3.358513"461004103797": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.744787"461014746633": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818608587", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.634804"461004051181": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818610234", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.229369"461004051190": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.497491"461004051201": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818612971", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
6.719273"461004106069": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
5.363896"461000818904": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
3.20129"461003059181": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.868748"461003092119": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818630154", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
4.629439"461003094101": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818634780", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.338359"461004879982": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818635116", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
3.726262"461000776572": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.607267"461003078907": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818640471", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.227127"461013114245": {"error": "ERROR_DENIED", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас есть неоплаченный в течение 5 дней с момента активации «Обещанный платеж»."},
5.936415"461003114265": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
1.769827"461002813416": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818650423", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.733339"461002813436": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818651164", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.429103"461012777979": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818652587", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.556464"461002776775": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818654152", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.635126"461002813441": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818654790", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.297382"461000967113": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
4.646503"461000981620": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
2.18046"461001122143": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
4.391838"461000963178": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
4.630326"461001069007": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
7.430697"461001125223": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
3.321579"461000963236": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
4.474531"461000943135": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
2.428651"461000943186": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818690628", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.483853"461001084780": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
3.272244"461002228567": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.665894"461001103366": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.269488"461004233251": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818698344", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.997507"461004103829": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
2.005113"461004194617": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818702356", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.67577"461004639067": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818705033", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.819216"461000818953": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
2.077983"461003073974": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818709943", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.115249"461012781127": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818712061", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.123402"461012815819": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818714187", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.141197"461000024716": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818716333", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.003527"461000024741": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.904861"461000053330": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.346155"461004856677": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818719601", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.631006"461003911991": {"error": "ERROR_DENIED", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас есть неоплаченный в течение 5 дней с момента активации «Обещанный платеж»."},
1.714081"461010632404": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818721962", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.487106"461013944390": {"error": "ERROR_DENIED", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас есть неоплаченный в течение 5 дней с момента активации «Обещанный платеж»."},
5.243981"461000633967": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
2.04222"461003776198": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818729740", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
3.864216"461003117467": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.822786"461003100593": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818735442", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.5405"461001784052": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
2.233533"461003771239": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
3.523472"461000615065": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818743760", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.209779"461000633904": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
2.682293"461004731783": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
6.628147"461004839194": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
3.817401"461000638523": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
1.726493"461004625974": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818759842", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
9.751936"461000634354": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
2.800432"461000672753": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818772409", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.213902"461003953947": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818774618", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.801097"461011650902": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818776435", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
8.816989"461002640674": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
0.310797"461002670969": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818785571", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
4.380298"461000675054": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
1.929947"461002800815": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818791883", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.482515"461000203480": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
5.181678"461003949640": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
1.856077"461011634093": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818801410", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.214583"461001634097": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.842625"461000656621": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818804489", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.863053"461002945408": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818806342", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.877581"461002945449": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818807228", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.124606"461000020278": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.862513"461003933928": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818811224", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
4.049531"461003950838": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818815290", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.788923"461003969173": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818817071", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.350806"461001691529": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818817428", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.275419"461001691571": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818817708", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.326207"461002655316": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818818040", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.276239"461002673873": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818818319", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.301879"461002673881": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818818625", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.884253"461010651198": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818820513", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.690709"461010651215": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818821200", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.428672"461002836218": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818822653", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.497745"461000281938": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
2.485851"461003953052": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818827639", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.264635"461001691575": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818827920", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
3.61433"461001783948": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
3.398318"461001783993": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
4.746427"461003827143": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.817243"461002947062": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818841503", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.707417"461002965546": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.956648"461001818635": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818845177", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.711544"461003791939": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818846899", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
5.956135"461003791951": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
4.806337"461004216215": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818857683", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.348793"461003621647": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
4.126698"461003660086": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
3.248321"461003624893": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818867423", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.275307"461004514941": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818867693", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.25805"461004515073": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818867963", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.296077"461004532618": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818868263", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.337729"461004479129": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818868598", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.268184"461004517262": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818868870", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.837228"461003639993": {"error": "ERROR_DENIED", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас есть неоплаченный в течение 5 дней с момента активации «Обещанный платеж»."},
2.407519"461002692762": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818874123", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.866957"461002639358": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818876004", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.18258"461000634313": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818878190", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
3.303832"461000634323": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
1.906907"461002781371": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.367366"461012798765": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818884769", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.68673"461003914220": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818886467", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.176506"461001650879": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818887646", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
3.83524"461002773204": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.892247"461000672756": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
3.157876"461002834241": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
5.031854"461002834170": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818900588", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.277188"461001813796": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818900871", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.569642"461003101613": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.296282"461001813520": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818903731", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.852044"461003776204": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818904599", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
3.166278"461003935571": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818907766", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.84724"461003935638": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818908613", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
5.848699"461002124510": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
3.547235"461002097148": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
0.664871"461002115715": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818918696", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.78497"461012061592": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818920486", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.800631"461002097074": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818922282", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
4.752649"461002097106": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
2.337155"461000126551": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.731676"461002518395": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818930126", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.685676"461002505784": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818930815", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.342725"461002121768": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
7.274568"461002097138": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
1.749986"461004752580": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818942195", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.270929"461004877787": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818942470", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.263668"461004788134": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818942728", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.253187"461004788145": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818943000", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.355441"461002075280": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818944358", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.447116"461002061571": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.299793"461004788187": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818946110", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.243273"461002407448": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818946366", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
6.679096"461000342965": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
6.519569"461004882782": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
2.116841"461000362999": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.74177"461000324509": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818963433", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.765199"461000324524": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818964211", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.957974"461000021711": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.147168"461003061086": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.832719"461003061106": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818969153", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.952869"461013061135": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818970111", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.291153"461004790940": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818970413", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.267038"461004790988": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818970684", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.537259"461002914296": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818972219", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.735376"461002769466": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818973963", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.658574"461002769540": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818974633", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.713573"461000671521": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.610056"461002782606": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818977956", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.352478"461002801230": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818979313", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.779379"461010528687": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818981083", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.725598"461000528693": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818981836", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.298221"461000489622": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818982130", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.832079"461000527965": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818983976", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
6.980313"461000206309": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
2.642318"461002539036": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.3433"461002499824": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622818993940", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.785337"461002627371": {"error": "ERROR_DENIED", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас есть неоплаченный в течение 5 дней с момента активации «Обещанный платеж»."},
5.413132"461002546024": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
4.303138"461002508111": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.399102"461002526712": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.820668"461004624602": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819006698", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.164218"461004787607": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819007858", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.029177"461004787646": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.924538"461002526727": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819009817", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.153131"461002548960": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.297811"461002638287": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819012279", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.27564"461001360405": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819012565", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.293746"461004353488": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819012855", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.269439"461001373419": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819013127", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.280957"461004488376": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819013424", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.847781"461004883260": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819015279", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.78981"461000322938": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
10.948448"461000302781": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
5.851435"461004704535": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
6.061225"461004794373": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
1.693016"461004668521": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819041634", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.996579"461000052959": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.718485"461003096351": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819044358", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.332051"461001252499": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819044692", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.326097"461001271123": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819045034", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.318831"461001271175": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819045348", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
3.468377"461000312270": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.304486"461001237467": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819049138", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.25096"461001219209": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819049390", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.269263"461001254698": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819049658", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.879577"461011273361": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819051541", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.263548"461001263365": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819051817", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.273392"461001227966": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819052093", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
3.885663"461001069948": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.990798"461011552671": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819057978", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.272374"461001275112": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819058256", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.107686"461001275190": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819060364", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.269033"461001222821": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819060632", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.600395"461001504883": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
4.849143"461003207324": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
1.818728"461003224824": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819069918", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.608783"461001069706": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819071536", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.334507"461000685274": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819071864", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.499319"461000628432": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.2986"461004516563": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819074655", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
5.015079"461003646282": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
3.325496"461003664542": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
2.426857"461000227164": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.277651"461004255543": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819085733", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.356145"461004201143": {"error": "ERROR_DENIED", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас есть неоплаченный в течение 5 дней с момента активации «Обещанный платеж»."},
2.047675"461004482197": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819090149", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
9.006059"461003630303": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
6.454358"461003630339": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
3.416265"461000228897": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819109050", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
3.998092"461000284159": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
1.915236"461000265612": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819114964", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.338182"461004385762": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819115306", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.299615"461003666544": {"error": "ERROR_DENIED", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас есть неоплаченный в течение 5 дней с момента активации «Обещанный платеж»."},
4.000251"461003680644": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819121615", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.332678"461003680661": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819121953", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.893789"461000287900": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.300566"461004498317": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819124168", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.333402"461004480670": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819124487", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.51731"461013629078": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819126035", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
4.559925"461003637143": {"error": "ERROR_DENIED", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас есть неоплаченный в течение 5 дней с момента активации «Обещанный платеж»."},
0.341527"461002514000": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819130935", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.305306"461002532460": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819131247", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.28206"461004806089": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819131540", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.968186"461003929389": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819133513", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.373973"461010670943": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819134891", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.452436"461010670962": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819135339", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.726701"461004715132": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819137069", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.661013"461003058033": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819138735", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.266946"461004825497": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819139018", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.270604"461004898208": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819139292", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.695914"461003080602": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819140982", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.639854"461002916329": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819141632", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.292881"461004627249": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819141927", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.268999"461004682187": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819142211", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.299687"461002370183": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819144503", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
5.595932"461004669358": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819150103", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.182165"461004776382": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.380476"461004812062": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622819153675", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
3.574814"461002370125": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
2.157404"461000365520": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.789228"461000345445": {"error": "ERROR_DENIED", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас есть неоплаченный в течение 5 дней с момента активации «Обещанный платеж»."},
