6.772932"461003639959": {"error": "ERROR_DENIED", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас есть неоплаченный в течение 5 дней с момента активации «Обещанный платеж»."},
3.55289"461010230585": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741273722", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.57396"461000249378": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.297658"461004514444": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741275604", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.563781"461000249497": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.292126"461004251843": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741277472", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.418931"461004216817": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741279898", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
4.004801"461000052951": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
0.298071"461002407783": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741284218", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.522632"461000363036": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
6.618098"461013061096": {"error": "ERROR_DENIED", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас есть неоплаченный в течение 5 дней с момента активации «Обещанный платеж»."},
0.797156"461002965763": {"error": "ERROR_DENIED", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас есть неоплаченный в течение 5 дней с момента активации «Обещанный платеж»."},
2.406543"461012949055": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741296569", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.149821"461003055051": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
2.31163"461002916308": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741301062", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.896567"461002916338": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741301973", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.915172"461002951781": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.306924"461004825225": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741304223", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.277806"461002653400": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741304497", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.20796"461001379908": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741306720", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
4.370579"461001398434": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.30547"461004504315": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741311415", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
4.343018"461001361757": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741315767", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.327491"461004359289": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741316104", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.264156"461004359334": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741316385", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.306497"461004343726": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741316696", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.301071"461002637893": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741316991", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.257569"461002657048": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741317261", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.25209"461004504214": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741317522", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.301013"461004734575": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741317819", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.292831"461004823695": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741318122", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.753792"461004769556": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.845099"461004769567": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.289158"461002126461": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741322037", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.293267"461002126472": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741322342", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.786291"461002115718": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741325131", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.304514"461004866225": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741325439", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
3.219625"461014760230": {"error": "ERROR_DENIED", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас есть неоплаченный в течение 5 дней с момента активации «Обещанный платеж»."},
0.302539"461004616789": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741328973", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.287476"461004700535": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741329265", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.318793"461004718880": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741329569", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.246814"461004718890": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741329852", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.840763"461002541888": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.712982"461002518401": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741334424", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
3.813781"461002505805": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741338249", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
8.788941"461002524424": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
1.604654"461002524443": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
2.912679"461004894762": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741351580", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.485397"461004769025": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741353094", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.276958"461004396548": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741353387", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.275287"461002690674": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741353671", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.311752"461001360440": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741353986", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.846372"461001362393": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741355854", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.301722"461002673522": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741356168", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.264126"461002692120": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741356442", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.284273"461001373402": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741356732", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.269554"461001374975": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741357002", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.289113"461001393627": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741357294", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.250179"461004359560": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741357560", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.300441"461004523606": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741357854", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.2535"461004523652": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741358122", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.278657"461004397054": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741358418", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.285212"461002636551": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741358700", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.30262"461001357045": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741359018", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.949747"461011379873": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741359966", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.282875"461004790906": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741360252", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.163394"461002965719": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741362419", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
8.297687"461003061088": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
2.778297"461003061091": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
0.300669"461004844104": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741373827", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
7.050722"461000302861": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
4.81458"461001525715": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
0.272198"461001267831": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741385981", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.297327"461001247861": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741386285", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.575982"461000330633": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.495631"461000350735": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741390367", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.989184"461000311000": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.298273"461001258311": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741392653", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.053915"461001526590": {"error": "ERROR_DENIED", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас есть неоплаченный в течение 5 дней с момента активации «Обещанный платеж»."},
0.309918"461001264668": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741394036", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.277348"461001264687": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741394314", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.700119"461000330653": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741395018", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.933119"461000350737": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
2.347959"461001256163": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741398309", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
4.931311"461003678559": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.859856"461001249535": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741405115", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.254655"461001276529": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741405377", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.866405"461001349774": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741407245", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.34967"461001349795": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741407556", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.250878"461001349735": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741407856", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.27172"461001349762": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741408133", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.97443"461001365210": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741410111", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.308504"461001230900": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741410416", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.264465"461001249545": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741410691", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
10.352778"461003237165": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
2.262217"461003237185": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
0.806309"461001525727": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741424129", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.284226"461001491120": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
2.192338"461011081201": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741428613", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.3652"461001081236": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.697117"461011267811": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741431677", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.780268"461011247836": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741433458", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.280747"461001247858": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741433754", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.105822"461001228036": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741435855", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.295546"461001263531": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741436153", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.254836"461001264683": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741436421", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.934428"461011211146": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741438360", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.270952"461001211235": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741438636", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
3.491439"461000350739": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
0.929166"461000350741": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
3.609812"461003238551": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741446678", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.183253"461001497812": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741448866", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.132912"461001071770": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741451004", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.104615"461010648495": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741453106", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
3.280207"461000628437": {"error": "ERROR_DENIED", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас есть неоплаченный в течение 5 дней с момента активации «Обещанный платеж»."},
4.095867"461003637209": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741460490", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
6.963805"461003677351": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
0.927419"461003631325": {"error": "ERROR_DENIED", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас есть неоплаченный в течение 5 дней с момента активации «Обещанный платеж»."},
0.273336"461004790956": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741468668", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.133041"461003112374": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741470807", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.154178"461004613508": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741472964", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.040342"461000053906": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741475016", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.847066"461000055705": {"error": "ERROR_DENIED", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас есть неоплаченный в течение 5 дней с момента активации «Обещанный платеж»."},
4.854509"461000297882": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
0.830154"461000297901": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.302903"461002392053": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741481853", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.225544"461000327320": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
6.533799"461000346125": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
1.2833"461004613516": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741491924", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
4.166982"461004846609": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741496095", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
7.894046"461000055684": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741503985", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.83708"461000055688": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
2.283735"461002086246": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
4.65166"461002098961": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
2.010144"461004661909": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
8.81133"461002115911": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
1.606327"461004876755": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741524214", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
5.313301"461002493126": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
1.942492"461002525329": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.477319"461002489834": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.650761"461004679926": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741534621", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.174778"461004876146": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
3.771521"461002678628": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
2.244363"461002508480": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
2.177571"461002494708": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.49886"461002530243": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741546511", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.484867"461002638865": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741548999", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.404988"461002694561": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.295901"461002670854": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741551692", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.296365"461001351906": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741552009", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.29494"461004376947": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741552300", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.82657"461002675390": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741554140", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.79104"461002675483": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741554935", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.306049"461001671932": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741555235", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.322928"461001671948": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741555566", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.278889"461001671995": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741555852", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.263629"461001671925": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741556133", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.268514"461001671939": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741556400", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.320717"461014522501": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741558722", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.291735"461002670548": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741559020", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.280997"461002691830": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741559312", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.300099"461001637679": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741559605", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.265811"461004522559": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741559885", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
10.186589"461002069544": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
1.418768"461004625219": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741571499", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.213643"461004805026": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1623741572708", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.595231"461002117931": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
