7.229289"461003639959": {"error": "ERROR_DENIED", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас есть неоплаченный в течение 5 дней с момента активации «Обещанный платеж»."},
2.908561"461010230585": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1624434501558", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.724602"461000249378": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.307471"461004514444": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1624434503601", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.593976"461000249497": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.330982"461004251843": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1624434505538", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.308036"461004216817": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1624434507863", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
4.396676"461000052951": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
0.281149"461002407783": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1624434512558", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.861141"461000363036": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
4.852555"461013061096": {"error": "ERROR_DENIED", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас есть неоплаченный в течение 5 дней с момента активации «Обещанный платеж»."},
0.742995"461002965763": {"error": "ERROR_DENIED", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас есть неоплаченный в течение 5 дней с момента активации «Обещанный платеж»."},
2.05929"461012949055": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1624434523107", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.384768"461003055051": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.910081"461002916308": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1624434527421", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.667021"461002916338": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1624434528081", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.574467"461002951781": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.312381"461004825225": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1624434529998", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.273107"461002653400": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1624434530287", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.590287"461001379908": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1624434532883", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
4.749446"461001398434": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.304371"461004504315": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1624434537944", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
3.777697"461001361757": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1624434541718", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.360738"461004359289": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1624434542082", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.341605"461004359334": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1624434542433", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.304512"461004343726": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1624434542740", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.337285"461002637893": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1624434543092", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.297934"461002657048": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1624434543392", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.352532"461004504214": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1624434543756", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.311171"461004734575": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1624434544072", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.29127"461004823695": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1624434544381", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.631037"461004769556": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.879149"461004769567": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.348777"461002126461": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1624434548230", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.315709"461002126472": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1624434548564", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
