6.995142"461003639959": {"error": "ERROR_DENIED", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас есть неоплаченный в течение 5 дней с момента активации «Обещанный платеж»."},
4.318046"461010230585": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711587893", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.66587"461000249378": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.285697"461004514444": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711589863", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.546984"461000249497": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.284866"461004251843": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711591706", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.465018"461004216817": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711594169", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
4.101966"461000052951": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
0.342281"461002407783": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711598619", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.789357"461000363036": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
5.914291"461013061096": {"error": "ERROR_DENIED", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас есть неоплаченный в течение 5 дней с момента активации «Обещанный платеж»."},
0.875988"461002965763": {"error": "ERROR_DENIED", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас есть неоплаченный в течение 5 дней с момента активации «Обещанный платеж»."},
2.290725"461012949055": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711610513", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.651074"461003055051": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
2.115054"461002916308": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711615288", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.784428"461002916338": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711616084", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.954211"461002951781": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.282473"461004825225": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711618324", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.276592"461002653400": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711618618", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.857292"461001379908": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711621481", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
3.855043"461001398434": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.2939"461004504315": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711625643", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
3.680751"461001361757": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711629329", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.274954"461004359289": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711629607", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.244466"461004359334": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711629859", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.313256"461004343726": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711630143", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.293765"461002637893": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711630467", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.260717"461002657048": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711630741", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.305032"461004504214": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711631038", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.322845"461004734575": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711631368", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.312472"461004823695": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711631680", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.837807"461004769556": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.986612"461004769567": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711635527", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.279965"461002126461": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711635809", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.238351"461002126472": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711636055", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.648861"461002115718": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711638707", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.265276"461004866225": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711638979", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
4.055977"461014760230": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711643033", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.28596"461004616789": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711643324", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.264551"461004700535": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711643600", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.266632"461004718880": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711643862", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.26902"461004718890": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711644136", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.976687"461002541888": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.538272"461002518401": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711648661", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
4.278152"461002505805": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711652942", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
8.347981"461002524424": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
0.899431"461002524443": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.77243"461004894762": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711663986", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.358784"461004769025": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711665356", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.279267"461004396548": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711665639", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.310151"461002690674": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711665949", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.302804"461001360440": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711666261", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.907236"461001362393": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711668138", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.316019"461002673522": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711668504", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.298651"461002692120": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711668785", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.2796"461001373402": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711669086", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.314509"461001374975": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711669415", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.266106"461001393627": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711669678", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.268088"461004359560": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711669950", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.317423"461004523606": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711670279", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.253943"461004523652": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711670546", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.305865"461004397054": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711670834", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.24682"461002636551": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711671109", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.281901"461001357045": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711671393", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.975241"461011379873": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711672380", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.299492"461004790906": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711672675", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.004491"461002965719": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711674690", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
9.171837"461003061088": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
2.662966"461003061091": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
0.290087"461004844104": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711686829", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
7.214859"461000302861": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
5.983152"461001525715": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
0.327509"461001267831": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711700364", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.300798"461001247861": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711700674", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
3.002005"461000330633": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.773384"461000350735": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711705467", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.810729"461000311000": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.286968"461001258311": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711708569", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.031372"461001526590": {"error": "ERROR_DENIED", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас есть неоплаченный в течение 5 дней с момента активации «Обещанный платеж»."},
0.339032"461001264668": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711709948", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.306696"461001264687": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711710259", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.703443"461000330653": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711710984", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.025493"461000350737": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
3.005524"461001256163": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711715017", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
7.298386"461003678559": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
2.754524"461001249535": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711725091", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.314596"461001276529": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711725400", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.233018"461001349774": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711727644", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.280428"461001349795": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711727932", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.285408"461001349735": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711728229", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.314061"461001349762": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711728550", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.057314"461001365210": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711730604", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.267863"461001230900": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711730883", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.27079"461001249545": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711731151", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
8.620658"461003237165": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
2.281475"461003237185": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
0.648061"461001525727": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711742720", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.493395"461001491120": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
2.319847"461011081201": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.238484"461001081236": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.611638"461011267811": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711750405", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
4.420459"461011247836": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
0.273557"461001247858": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711755110", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.115184"461001228036": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711757229", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.276993"461001263531": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711757503", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.294153"461001264683": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711757801", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.73241"461011211146": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711759544", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.289387"461001211235": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711759839", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
3.19144"461000350739": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
0.940319"461000350741": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
3.583356"461003238551": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711767569", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.258149"461001497812": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711769834", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.226864"461001071770": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711772055", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.280428"461010648495": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711774345", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
3.293669"461000628437": {"error": "ERROR_DENIED", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас есть неоплаченный в течение 5 дней с момента активации «Обещанный платеж»."},
3.864159"461003637209": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711781519", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
7.172747"461003677351": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
1.096971"461003631325": {"error": "ERROR_DENIED", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас есть неоплаченный в течение 5 дней с момента активации «Обещанный платеж»."},
0.255036"461004790956": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711790065", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.015112"461003112374": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711792081", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.106157"461004613508": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711794204", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.098141"461000053906": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711796296", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.652389"461000055705": {"error": "ERROR_DENIED", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас есть неоплаченный в течение 5 дней с момента активации «Обещанный платеж»."},
5.315913"461000297882": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
0.903597"461000297901": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.281395"461002392053": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711803486", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.385472"461000327320": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711805865", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
6.757779"461000346125": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
1.641958"461004613516": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711814282", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
4.512186"461004846609": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711818802", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
8.572079"461000055684": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711827378", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.284355"461000055688": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711828675", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.313793"461002086246": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
4.970204"461002098961": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
2.052251"461004661909": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711838025", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
10.185166"461002115911": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
1.595613"461004876755": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711849818", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
5.199308"461002493126": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
2.319601"461002525329": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.915889"461002489834": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711859259", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.076029"461004679926": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711861338", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.96456"461004876146": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
3.871838"461002678628": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.941945"461002508480": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
2.096427"461002494708": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711871242", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.652529"461002530243": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711872896", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.911561"461002638865": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711874810", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.202087"461002694561": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.269623"461002670854": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711877303", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.29001"461001351906": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711877594", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.302415"461004376947": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711877907", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.846497"461002675390": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711879759", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.698349"461002675483": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711880469", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.321922"461001671932": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711880776", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.296994"461001671948": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711881093", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.29027"461001671995": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711881389", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.289046"461001671925": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711881678", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.28991"461001671939": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711881978", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
3.007333"461014522501": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711884998", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.281433"461002670548": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711885280", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.288062"461002691830": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711885569", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.308885"461001637679": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711885896", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.284838"461004522559": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711886192", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
10.643216"461002069544": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
1.854523"461004625219": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711898692", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.202197"461004805026": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711899904", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.59051"461002117931": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.472882"461002082444": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711903979", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.539745"461002082530": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.840036"461004822601": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711907377", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.422411"461004822549": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
11.841551"461003677202": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
7.01096"461003623465": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711927672", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.902359"461004711057": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711929582", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.947944"461003493803": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711931535", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.640315"461003493809": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711934135", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.932422"461013493857": {"error": "ERROR_DENIED", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас есть неоплаченный в течение 5 дней с момента активации «Обещанный платеж»."},
3.493063"461003670938": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
0.306572"461004086797": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711939927", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
4.06889"461003388387": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711943999", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
3.698608"461003388433": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711947702", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.94955"461003388434": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711948658", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.602224"461001536423": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.846391"461011531380": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711953138", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.94321"461010629708": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711955088", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.307311"461001258230": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711955396", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.297204"461001273357": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711955692", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.340493"461001228773": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711958044", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.28562"461001228838": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711958340", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.262843"461001247339": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711958613", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.254391"461001247358": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711958872", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.934401"461001124497": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.624217"461010630697": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711963441", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.977808"461004532594": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.92821"461013642137": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.276742"461001241709": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711967642", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
4.197142"461000312273": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
0.321981"461001237594": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711972169", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.271729"461001256145": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711972436", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.03755"461011273410": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.273146"461001273431": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711974768", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.271922"461001277209": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711975047", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.25934"461001247878": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711975313", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.270236"461001271157": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711975587", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
4.441438"461003347937": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
1.955358"461002793331": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711981993", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.04729"461003347923": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711984043", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.857449"461013347969": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711984907", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.069756"461002832895": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
2.032691"461002794669": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
3.568603"461002209972": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711992585", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.702528"461002230097": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
3.682412"461000926754": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622711998979", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.763069"461000949441": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
2.033693"461002206530": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
2.339158"461002234006": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
2.189382"461000948986": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712008331", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
10.297879"461001089747": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.282215"461002397287": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712018923", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.260293"461002397301": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712019181", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.180143"461002231671": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712021373", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.29496"461002343776": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712021663", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.281965"461000926773": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
4.491319"461001120164": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712027457", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
8.798903"461003114267": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
2.21176"461003092160": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712038468", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.930278"461013060313": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712040404", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.347677"461003096891": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712041756", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.284644"461004736226": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712042052", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.269425"461004664170": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712042327", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
4.985729"461003350527": {"error": "ERROR_DENIED", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас есть неоплаченный в течение 5 дней с момента активации «Обещанный платеж»."},
1.821669"461002830227": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712049133", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.334993"461002776710": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712050486", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.285877"461004896358": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712050779", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.719443"461003110817": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712052499", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.628526"461003110823": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712053135", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.286875"461004861060": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712053429", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.334283"461004896416": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712053764", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
7.003929"461003905298": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
1.231459"461003903027": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712062005", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": "Unknown error"}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.079631"461003903036": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712064100", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.450707"461003926100": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712066548", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
8.18413"461000615133": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712074736", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.289038"461004839233": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712075033", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.035491"461003930454": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712077078", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.190443"461003771260": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712079268", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.724811"461002970118": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712080997", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
5.538376"461001818434": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.317082"461002970273": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712087872", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.645387"461012949745": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712089522", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.159167"461001779365": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712091682", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.812331"461003792798": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712093503", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
6.366163"461003827150": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
2.249527"461002802812": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712102129", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.67776"461002821415": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712103811", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
8.083324"461002768862": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.935028"461012804363": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712113833", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.919598"461010613114": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712115763", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.64001"461010613137": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712116405", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.918118"461002927888": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712118327", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
7.274159"461003932732": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
1.58237"461003951039": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712127192", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.31549"461002095389": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712127513", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.806058"461002788826": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712129329", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.517975"461002824363": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712130855", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
5.078981"461000654554": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
7.92692"461000656900": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
4.330261"461002093258": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
0.467782"461012804366": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712148675", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.748772"461002781498": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712150430", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.015803"461000052352": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.664756"461000022919": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712154118", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.658547"461003926090": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712154791", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
3.281409"461003926096": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.49313"461010612547": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712159581", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.940821"461004714852": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712161529", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.271923"461004838975": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712161819", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
5.136183"461003948725": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.271706"461001691524": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712167253", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.638824"461012804475": {"error": "ERROR_DENIED", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас есть неоплаченный в течение 5 дней с момента активации «Обещанный платеж»."},
3.241119"461004252550": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.921037"461014532263": {"error": "ERROR_DENIED", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас есть неоплаченный в течение 5 дней с момента активации «Обещанный платеж»."},
0.261879"461004479512": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712173338", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.260259"461004532811": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712173599", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
7.331986"461003904417": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712180906", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.379717"461003904385": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
2.274358"461000636861": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
2.222348"461002797217": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
3.44202"461002797244": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
1.249272"461000052375": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.439888"461000049200": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
6.293407"461003934956": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
5.04257"461000671384": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712205329", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.197571"461002815858": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712206534", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.807803"461002815873": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712207347", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.674965"461000052346": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712208026", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.264594"461000052374": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
3.499908"461000050619": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.989571"461003916451": {"error": "ERROR_DENIED", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас есть неоплаченный в течение 5 дней с момента активации «Обещанный платеж»."},
4.027487"461003916467": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712218829", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
6.778994"461003916678": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
2.026293"461000304544": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.77867"461000304548": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712228422", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.338558"461000343013": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712229773", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
6.845256"461004668877": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.89073"461004668587": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712238517", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
3.367177"461000023489": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712241891", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.187979"461000020440": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712244083", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.868213"461012409289": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712245944", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.827764"461002121775": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
0.800444"461002097150": {"error": "ERROR_DENIED", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас есть неоплаченный в течение 5 дней с момента активации «Обещанный платеж»."},
5.441656"461012520365": {"error": "ERROR_DENIED", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас есть неоплаченный в течение 5 дней с момента активации «Обещанный платеж»."},
0.279011"461004396672": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712254315", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.308167"461002670767": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712254642", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
9.473545"461002638814": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
1.309735"461001398498": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.135012"461001361935": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712266579", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.287374"461004391070": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712267866", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.274439"461002656377": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712268153", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.592442"461002674951": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712269741", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.288384"461001405567": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712270037", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.645235"461014396206": {"error": "ERROR_DENIED", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас есть неоплаченный в течение 5 дней с момента активации «Обещанный платеж»."},
1.640647"461003078241": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712274335", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.165618"461002970481": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712275509", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.271264"461004718867": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712275778", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["promisedPayments"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisedPaymentsHistory', errors=[{'loc': ('promisedPayments',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
0.274179"461004754121": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712276057", "status": "Error", "errorCode": "BIZ-001", "errorDescription": "Data not found fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
1.410713"461003080512": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712277477", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.867075"461003080517": {"error": "ERROR_DATA_NOT_FOUND", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас отсутствует задолженность за услуги связи."},
1.440048"461002964108": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712281795", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
2.274047"461012914213": {"canActivatePromisedPayment": true, "status": null, "endDate": null, "summ": null},
1.531393"461002931245": {"error": "EX_SYSTEM_ERROR", "detail": {"response": {"timestamp": "1622712285609", "status": "Error", "errorCode": "SYS-001", "errorDescription": "General system fault", "errorMessage": ""}, "errors": [{"loc": ["canActivatePromisedPayment"], "msg": "field required", "type": "value_error.missing"}]}, "message": "Error during parsing the response from the remote system", "reason": "ValidationError(model='ExternalPromisePaymentInfo', errors=[{'loc': ('canActivatePromisedPayment',), 'msg': 'field required', 'type': 'value_error.missing'}])"},
3.498082"461014668428": {"error": "ERROR_DENIED", "detail": null, "message": "Заявка на активацию «Обещанного платежа» не может быть принята. У Вас есть неоплаченный в течение 5 дней с момента активации «Обещанный платеж»."},
